# Generated by Django 6.0.7 on 2026-07-15 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(help_text="Driver's current location", max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup location', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff location', max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, help_text='Current HOS cycle hours used', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLANNED', 'Planned'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
