# Generated by Django 6.0.7 on 2026-07-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
                ('cycle_hours_used', models.FloatField()),
                ('cycle_type', models.CharField(choices=[('60', '60-hour / 7-day'), ('70', '70-hour / 8-day')], default='70', max_length=2)),
                ('adverse_conditions', models.BooleanField(default=False)),
                ('remaining_driving_hours', models.FloatField(default=0)),
                ('remaining_on_duty_hours', models.FloatField(default=0)),
                ('remaining_cycle_hours', models.FloatField(default=0)),
                ('break_required', models.BooleanField(default=False)),
                ('off_duty_reset_required', models.BooleanField(default=False)),
                ('hos_violations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
